server:
  port: 8066
spring:
  application:
    name: cloud-config
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          # git仓库的地址
          uri: https://github.com/x157123/spring-cloud
          # git仓库地址下的相对地址，可以配置多个，用,分割
          searchPaths: cloud-config/src/main/resources/config
          # git仓库的账号
          username: x157123@126.com
          # git仓库的密码
          password: 5dp4FmqXfDNHE46
          force-pull: true
      label: master
  # http://127.0.0.1:15672 管理地址端口
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: liulei
    password: liulei
# 指定注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    preferIpAddress: true
