server:
  port: 80

spring:
  application:
    name: camunda
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cloud_camunda?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456

camunda:
  bpm:
    admin-user:
      id: zs
      password: zs
      first-name: zs
    filter:
      create: All tasks