server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost/testuser?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  # http://127.0.0.1:15672 管理地址端口
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: liulei
    password: liulei
