server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 服务名小写
          lower-case-service-id: true
#  #配置zipkin
#  zipkin:
#    base-url: http://127.0.0.1:9411
#    #discovery-client-enabled: false  # 不要让nacos把zipkin注册进去（可以不写）
#  sleuth:
#    sampler:
#      probability: 1.0

# 指定注册中心的地址
eureka:
  client:
    serviceUrl:
#      defaultZone: http://cloud-eureka-01.default.svc.cluster.local:8000/eureka
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
api:
  server:
    exclude: [ eureka,gateway,cloud-config ]
knife4j:
  enable: true
  # 指定服务发现的模式聚合微服务文档
  strategy: discover
