server:
  port: 8099
  #address: 127.0.0.1
  #sessionTimeout: 30
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  kafka:
    #本地虚拟机kafka伪集群
    bootstrap-servers: 192.168.10.176:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288
      #自定义的topic
      myTopic: publicall.*
      myTopic1: DBTestServer.public.p_sg_com_pub_edu_2020
      myTopic2: DBTestServer.public.p_sg_com_pub_edu_2021
    consumer:
      group-id: default-group   #默认组id  后面会配置多个消费者组
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: false   #关闭自动提交 改由spring-kafka提交
      auto-commit-interval: 100
      max-poll-records: 20      #批量消费 一次接收的最大数量

