server:
  port: 8066
spring:
  application:
    name: cloud-config
  cloud:
    bus:
      trace:
        enabled: true
    config:
      server:
        git:
          # git仓库的地址
          uri: https://gitee.com/x157123/springCloud.git
          # git仓库地址下的相对地址，可以配置多个，用,分割
          searchPaths: config-repo
          # git仓库的账号
          username: x157123@126.com
          # git仓库的密码
          password: xujia4209
          default-label: master
  # http://198.46.158.227:15672 管理地址端口
  rabbitmq:
    host: 198.46.158.227
    port: 5672
    username: guest
    password: guest
# 指定注册中心的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    preferIpAddress: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
